project:
  type: book
  output-dir: "docs"
  preview:
    port: 4200
execute:
  cache: true
jupyter: python3

book:
  title: "Incidencia Delictiva Estatal"
  output-file: "Incidencia_Delicitiva_Estatal.html"
  subtitle: "(México 2015 - 2025)"
  author:
    - name: "Méndez Ávila Luis Geovanni"
      email: "lgma77@ciencias.unam.mx"
    - name: "Paredes Zamudio Luis Daniel"
      email: "danielparedes@ciencias.unam.mx"
    - name: "Sánchez Rosas Roberto Samuel"
      email: "samuel03srciencias.unam.mx"
  date: "2026-06-10"
  chapters:
    - index.qmd
    - chapters/eda.qmd
    - chapters/models.qmd
    - chapters/clustering.qmd
    - chapters/conclusiones.qmd
  #cover-image: "images/cover.png"
  favicon: "images/favicon.png"
  search: true
  repo-url: https://github.com/wallsified/proyecto-final-aymdd"
  repo-actions: [edit]
  downloads: [pdf]
  page-footer:
    left: "Facultad de Ciencias, Ciencias de la Computación, UNAM"
    center: "© 2026 Méndez Ávila, Paredes Zamudio y Sánchez Rosas"
    right: "Almacenes y Minería de Datos 26-2"
  page-navigation: true

bibliography: "reports/references.bib"
nocite: |
  @*
theme: ["styles/nord.scss"]
lang: "es"

format:
  html:
    citeproc: true
    citations-hover: true
    citation-location: document
    html-math-method: katex
    code-fold: true
    code-summary: "Mostrar código"
    code-block-border-left: true
    code-line-numbers: true
    code-copy: true
    code-link: true
    syntax-highlighting: nord
    toc: true
    toc-depth: 3
    toc-title: "Contenido del Documento"
    toc-location: left
    fig-align: center
    smooth-scroll: true
    number-sections: false
    number-depth: 3
    code-links:
      - text: "Repositorio del Proyecto"
        href: "https://github.com/wallsified/proyecto-final-aymdd"
        icon: "github"
      - text: "Presentación"
        href: "example.com"
        icon: "easel-fill"
      - text: "Descargar PDF"
        href: "example.com"
        icon: "file-earmark-pdf-fill"
    grid:
      # verificar tamaños para ajustar en la mayoria de pantallas
        sidebar-width: 500px
        #margin-width: 0px
        #gutter-width: 50px
    page-navigation: false
    page-layout: full
