title: "Incidencia Delictiva Estatal"
subtitle: "(México 2015 - 2025)"
author:
  - name: "Méndez Ávila Luis Geovanni"
    email: "lgma77@ciencias.unam.mx"
  - name: "Paredes Zamudio Luis Daniel"
    email: "danielparedes@ciencias.unam.mx"
  - name: "Sánchez Rosas Roberto Samuel"
    email: "samuel03srciencias.unam.mx"
preview:
  port: 4200
execute:
  cache: true
jupyter: python3
lang: "es"
favicon: "images/favicon.png"
html-math-method: katex

format:
  revealjs:
    theme: "styles/nord.scss"
    slide-number: true
    code-fold: true
    echo: true
    fig-align: center
    transition: slide
    highlight-style: nord
    logo: "images/logos_unam.png"
    width: 1920
    height: 1080
    preview-links: auto
    embed-resources: true
    history: false
    multiplex: true
    autoPlayMedia: true
    touch: true
    footer: "Incidencia Delictiva Estatal (México 2015 - 2025)"
    fig-width: 6
    fig-height: 4
    fig-dpi: 150
    code-tools: false

bibliography: "references.bib"
nocite: |
  @*