<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.35">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Clustering y Análisis de Componentes Principales – Incidencia Delictiva Estatal</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/favicon.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-6429fa8ad5f20ae2e04e859bb353eb37.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-ea477a513a41e91311949efbdda462c8.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/clustering.html"><span class="chapter-title">Clustering y Análisis de Componentes Principales</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Incidencia Delictiva Estatal</a>
        <div class="sidebar-tools-main">
    <a href="https://github.com/wallsified/proyecto-final-aymdd&quot;" title="Ejecutar el código" class="quarto-navigation-tool px-1" aria-label="Ejecutar el código"><i class="bi bi-github"></i></a>
    <a href="../Incidencia_Delicitiva_Estatal.html.pdf" title="Descargar PDF" class="quarto-navigation-tool px-1" aria-label="Descargar PDF"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container">
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container">
  <a href="../index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Introducción</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container">
  <a href="../chapters/eda.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Análisis Exploratorio de Datos</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container">
  <a href="../chapters/models.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Modelos</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container">
  <a href="../chapters/clustering.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Clustering y Análisis de Componentes Principales</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container">
  <a href="../chapters/conclusiones.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Conclusiones</span></a>
  </div>
</li>
    </ul>
    </div>
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contenido del Documento</h2>

  <ul>
  <li><a href="#por-qué-se-decidio-usar-k-means" id="toc-por-qué-se-decidio-usar-k-means" class="nav-link active" data-scroll-target="#por-qué-se-decidio-usar-k-means">¿Por qué se decidio usar K-Means?</a></li>
  <li><a href="#preparación-de-los-datos-y-construcción-de-la-matriz-de-proporciones" id="toc-preparación-de-los-datos-y-construcción-de-la-matriz-de-proporciones" class="nav-link" data-scroll-target="#preparación-de-los-datos-y-construcción-de-la-matriz-de-proporciones">Preparación de los Datos y Construcción de la Matriz de Proporciones</a>
  <ul class="collapse">
  <li><a href="#consideración-sobre-la-dimensionalidad-y-visualización" id="toc-consideración-sobre-la-dimensionalidad-y-visualización" class="nav-link" data-scroll-target="#consideración-sobre-la-dimensionalidad-y-visualización">Consideración sobre la Dimensionalidad y Visualización</a></li>
  </ul></li>
  <li><a href="#selección-del-número-óptimo-de-clusters" id="toc-selección-del-número-óptimo-de-clusters" class="nav-link" data-scroll-target="#selección-del-número-óptimo-de-clusters">Selección del Número Óptimo de Clusters</a></li>
  <li><a href="#resultados-de-la-matriz-de-proporciones-y-perfil-de-clusters" id="toc-resultados-de-la-matriz-de-proporciones-y-perfil-de-clusters" class="nav-link" data-scroll-target="#resultados-de-la-matriz-de-proporciones-y-perfil-de-clusters">Resultados de la Matriz de Proporciones y Perfil de Clusters</a></li>
  <li><a href="#interpretacion-de-los-clusters" id="toc-interpretacion-de-los-clusters" class="nav-link" data-scroll-target="#interpretacion-de-los-clusters">Interpretacion de los Clusters</a>
  <ul class="collapse">
  <li><a href="#perfil-de-violencia-contra-las-personas" id="toc-perfil-de-violencia-contra-las-personas" class="nav-link" data-scroll-target="#perfil-de-violencia-contra-las-personas">#0 – Perfil de Violencia contra las Personas</a></li>
  <li><a href="#perfil-diversificado-de-otros-bienes-jurídicos" id="toc-perfil-diversificado-de-otros-bienes-jurídicos" class="nav-link" data-scroll-target="#perfil-diversificado-de-otros-bienes-jurídicos">#1 – Perfil Diversificado de Otros Bienes Jurídicos</a></li>
  <li><a href="#perfil-familiar-y-de-libertad-personal" id="toc-perfil-familiar-y-de-libertad-personal" class="nav-link" data-scroll-target="#perfil-familiar-y-de-libertad-personal">#2 – Perfil Familiar y de Libertad Personal</a></li>
  <li><a href="#perfil-patrimonial" id="toc-perfil-patrimonial" class="nav-link" data-scroll-target="#perfil-patrimonial">#3 – Perfil Patrimonial</a></li>
  <li><a href="#tabla-de-segmentación" id="toc-tabla-de-segmentación" class="nav-link" data-scroll-target="#tabla-de-segmentación">Tabla de Segmentación</a></li>
  </ul></li>
  <li><a href="#proyección-pca" id="toc-proyección-pca" class="nav-link" data-scroll-target="#proyección-pca">Proyección PCA</a></li>
  <li><a href="#perfiles-bajo-la-proyección-pca" id="toc-perfiles-bajo-la-proyección-pca" class="nav-link" data-scroll-target="#perfiles-bajo-la-proyección-pca">Perfiles bajo la Proyección PCA</a>
  <ul class="collapse">
  <li><a href="#perfil-diversificado" id="toc-perfil-diversificado" class="nav-link" data-scroll-target="#perfil-diversificado">#1 - Perfil Diversificado</a></li>
  <li><a href="#y-2---perfiles-de-violencia-y-entorno-familiar" id="toc-y-2---perfiles-de-violencia-y-entorno-familiar" class="nav-link" data-scroll-target="#y-2---perfiles-de-violencia-y-entorno-familiar">#0 y #2 - Perfiles de Violencia y Entorno Familiar</a></li>
  <li><a href="#perfil-patrimonial-1" id="toc-perfil-patrimonial-1" class="nav-link" data-scroll-target="#perfil-patrimonial-1">#3 - Perfil Patrimonial</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/wallsified/proyecto-final-aymdd&quot;/edit/main/chapters/clustering.qmd" class="toc-action"><i class="bi bi-github"></i>Editar esta página</a></li></ul></div><div class="quarto-code-links"><h2>Enlaces de código</h2><ul><li><a href="https://github.com/wallsified/proyecto-final-aymdd"><i class="bi bi-github"></i>Repositorio del Proyecto</a></li><li><a href="example.com"><i class="bi bi-easel-fill"></i>Presentación</a></li><li><a href="example.com"><i class="bi bi-file-earmark-pdf-fill"></i>Descargar PDF</a></li></ul></div></nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content column-page-right" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Clustering y Análisis de Componentes Principales</span></h1>
</div>



<div class="quarto-title-meta column-page-right">




  </div>



</header>


<p>El objetivo de este módulo es identificar segmentos, perfiles y patrones latentes en la incidencia delictiva de las 32 entidades federativas de México mediante técnicas de agrupamiento no supervisado utilizando el algoritmo K-Means.</p>
<p>A diferencia de un análisis basado en el volumen total de delitos, el cual puede verse influenciado por factores como el tamaño poblacional o la concentración urbana de cada entidad, este estudio se centra en la proporción de participación de los siete Bienes Jurídicos Afectados registrados en cada estado. De esta forma, el análisis busca caracterizar la composición relativa de la actividad delictiva en cada entidad, independientemente de su magnitud absoluta.</p>
<p>Bajo este enfoque, la pregunta principal que guía el análisis es:</p>
<blockquote class="blockquote">
<p><em>¿Qué tipo de delincuencia predomina en cada entidad federativa y qué estados comparten perfiles delictivos similares?</em></p>
</blockquote>
<section id="por-qué-se-decidio-usar-k-means" class="level1">
<h1>¿Por qué se decidio usar K-Means?</h1>
<p>Se seleccionó K-Means como algoritmo de agrupamiento debido a que las variables utilizadas corresponden a proporciones normalizadas de incidencia delictiva, generando un espacio de características continuo en el que la distancia euclidiana constituye una medida adecuada de similitud.</p>
<p>Adicionalmente, el análisis se realiza sobre un conjunto reducido de observaciones (32 entidades federativas), situación en la que los métodos basados en densidad pueden presentar una alta sensibilidad a la configuración de parámetros y producir agrupamientos poco estables.</p>
<p>Finalmente, K-Means genera centroides explícitos para cada grupo, lo que permite caracterizar e interpretar los perfiles criminológicos resultantes mediante el comportamiento promedio de los bienes jurídicos afectados en cada cluster.</p>
</section>
<section id="preparación-de-los-datos-y-construcción-de-la-matriz-de-proporciones" class="level1">
<h1>Preparación de los Datos y Construcción de la Matriz de Proporciones</h1>
<p>Con el fin de identificar patrones en la composición de la incidencia delictiva y evitar que los agrupamientos estuvieran determinados principalmente por el tamaño poblacional o el volumen total de delitos de cada entidad, se implementaron las siguientes transformaciones mediante la clase <code>CrimeClusteringPipeline</code>:</p>
<ul>
<li><p><strong>Agrupación por Bien Jurídico</strong>: Los distintos tipos y subtipos de delitos se agruparon en las siete categorías de Bien Jurídico Afectado definidas en el conjunto de datos. Esto permitió reducir la dimensionalidad y obtener una representación más interpretable del fenómeno delictivo.</p></li>
<li><p><strong>Normalización por Fila (Proporciones)</strong>: Para cada entidad federativa se calculó la proporción que representa cada bien jurídico respecto al total de delitos registrados en dicha entidad. Se usó la siguiente fórmula: <span class="math display">pi = \frac{Delitos_i}{\sum_j Delitos_j}</span></p></li>
</ul>
<p>De esta manera, cada estado quedó representado por un vector de siete proporciones cuya suma es igual a uno, permitiendo comparar la estructura relativa de la incidencia delictiva independientemente de su magnitud absoluta.</p>
<ul>
<li><strong>Estandarización (<code>StandardScaler</code>)</strong>: Aunque todas las variables fueron previamente transformadas a proporciones, los distintos bienes jurídicos presentan niveles de variabilidad diferentes entre entidades federativas. La estandarización permite que cada dimensión contribuya de forma equilibrada al cálculo de las distancias euclidianas utilizadas por K-Means, evitando que las categorías con mayor dispersión dominen el proceso de agrupamiento.</li>
</ul>
<div id="clustering-pipe-matrix" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Mostrar código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1"></a><span class="im">import</span> sys</span>
<span id="cb1-2"><a href="#cb1-2"></a><span class="im">from</span> pathlib <span class="im">import</span> Path</span>
<span id="cb1-3"><a href="#cb1-3"></a></span>
<span id="cb1-4"><a href="#cb1-4"></a><span class="co"># Resuelve el problema de las ubicaciones de los scripts</span></span>
<span id="cb1-5"><a href="#cb1-5"></a>sys.path.insert(<span class="dv">0</span>, <span class="bu">str</span>(Path.cwd().parent))</span>
<span id="cb1-6"><a href="#cb1-6"></a></span>
<span id="cb1-7"><a href="#cb1-7"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-8"><a href="#cb1-8"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-9"><a href="#cb1-9"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-10"><a href="#cb1-10"></a></span>
<span id="cb1-11"><a href="#cb1-11"></a><span class="im">from</span> src <span class="im">import</span> config</span>
<span id="cb1-12"><a href="#cb1-12"></a><span class="im">from</span> src.data <span class="im">import</span> DataRepository</span>
<span id="cb1-13"><a href="#cb1-13"></a><span class="im">from</span> src.clustering <span class="im">import</span> CrimeClusteringPipeline</span>
<span id="cb1-14"><a href="#cb1-14"></a></span>
<span id="cb1-15"><a href="#cb1-15"></a><span class="co"># Tema visual por defecto del proyecto.</span></span>
<span id="cb1-16"><a href="#cb1-16"></a>sns.set_theme(style<span class="op">=</span>config.SEABORN_THEME, palette<span class="op">=</span>config.PLOT_PALETTE)</span>
<span id="cb1-17"><a href="#cb1-17"></a></span>
<span id="cb1-18"><a href="#cb1-18"></a><span class="co"># Cargar el dataset limpio</span></span>
<span id="cb1-19"><a href="#cb1-19"></a>repo <span class="op">=</span> DataRepository(config.PROCESSED_CSV)</span>
<span id="cb1-20"><a href="#cb1-20"></a>dataframe <span class="op">=</span> repo.load()</span>
<span id="cb1-21"><a href="#cb1-21"></a></span>
<span id="cb1-22"><a href="#cb1-22"></a><span class="co"># Inicializar el pipeline de agrupamiento</span></span>
<span id="cb1-23"><a href="#cb1-23"></a>clustering_pipe <span class="op">=</span> CrimeClusteringPipeline()</span>
<span id="cb1-24"><a href="#cb1-24"></a></span>
<span id="cb1-25"><a href="#cb1-25"></a><span class="co"># Transformar los datos y generar la matriz estandarizada</span></span>
<span id="cb1-26"><a href="#cb1-26"></a>matrix_pct <span class="op">=</span> clustering_pipe.fit_transform(dataframe)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[Clustering] Matriz macro preparada con 32 estados y 7 variables (Bienes Jurídicos).
[Clustering] El plano visual (PCA 2D) captura el 55.32% de la varianza total de estas categorías.</code></pre>
</div>
</div>
<section id="consideración-sobre-la-dimensionalidad-y-visualización" class="level2">
<h2 class="anchored" data-anchor-id="consideración-sobre-la-dimensionalidad-y-visualización">Consideración sobre la Dimensionalidad y Visualización</h2>
<p>Con el propósito de visualizar los resultados del agrupamiento, se empleó un modelo de Análisis de Componentes Principales (PCA) configurado con dos componentes principales.</p>
<p>Es importante destacar que el algoritmo K-Means fue entrenado utilizando las siete variables originales estandarizadas, conservando así la totalidad de la información disponible para el proceso de agrupamiento. El PCA se utilizó únicamente como una técnica de reducción de dimensionalidad para representar gráficamente los resultados en un plano bidimensional.</p>
<p>La proyección obtenida mediante las dos primeras componentes principales explica el 55.32% de la varianza total de los datos. Si bien esta representación no captura la totalidad de la estructura presente en el espacio original de siete dimensiones, proporciona una aproximación visual adecuada de los patrones principales y permite interpretar de forma intuitiva la separación entre los grupos identificados por K-Means. La información restante permanece contenida en las dimensiones no representadas gráficamente, pero sí fue considerada durante el proceso de agrupamiento.</p>
</section>
</section>
<section id="selección-del-número-óptimo-de-clusters" class="level1">
<h1>Selección del Número Óptimo de Clusters</h1>
<p>Para determinar la estructura de agrupamiento más adecuada de las entidades federativas, se evaluaron simultáneamente el Método del Codo (Inercia) y la evolución del Coeficiente de Silueta en un rango de entre 2 y 8 clústers.</p>
<div id="cell-k-clusters-selection" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Mostrar código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1"></a><span class="co"># Calcular las métricas de Inercia y Silueta para rangos de K del 2 al 8</span></span>
<span id="cb3-2"><a href="#cb3-2"></a>metrics <span class="op">=</span> clustering_pipe.evaluate_k_options(max_k<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb3-3"><a href="#cb3-3"></a></span>
<span id="cb3-4"><a href="#cb3-4"></a><span class="co"># Configurar el lienzo para mostrar ambas gráficas una al lado de la otra</span></span>
<span id="cb3-5"><a href="#cb3-5"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">2</span>, <span class="dv">1</span>, figsize<span class="op">=</span>(<span class="dv">7</span>, <span class="dv">7</span>), dpi<span class="op">=</span>config.PLOT_DPI)</span>
<span id="cb3-6"><a href="#cb3-6"></a></span>
<span id="cb3-7"><a href="#cb3-7"></a><span class="co"># Gráfica izquierda: Método del Codo (Inercia)</span></span>
<span id="cb3-8"><a href="#cb3-8"></a>sns.lineplot(x<span class="op">=</span>metrics[<span class="st">"k"</span>], y<span class="op">=</span>metrics[<span class="st">"inertia"</span>], marker<span class="op">=</span><span class="st">"o"</span>, ax<span class="op">=</span>axes[<span class="dv">0</span>], color<span class="op">=</span><span class="st">"royalblue"</span>, linewidth<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb3-9"><a href="#cb3-9"></a>axes[<span class="dv">0</span>].set_title(<span class="st">"Curva del Codo"</span>)</span>
<span id="cb3-10"><a href="#cb3-10"></a>axes[<span class="dv">0</span>].set_xlabel(<span class="st">"Número de Grupos (K)"</span>)</span>
<span id="cb3-11"><a href="#cb3-11"></a>axes[<span class="dv">0</span>].set_ylabel(<span class="st">"Inercia (Suma de Cuadrados)"</span>)</span>
<span id="cb3-12"><a href="#cb3-12"></a>axes[<span class="dv">0</span>].grid(<span class="va">True</span>)</span>
<span id="cb3-13"><a href="#cb3-13"></a></span>
<span id="cb3-14"><a href="#cb3-14"></a><span class="co"># Gráfica derecha: Evolución de la Silueta (Silhouette Score)</span></span>
<span id="cb3-15"><a href="#cb3-15"></a>sns.lineplot(x<span class="op">=</span>metrics[<span class="st">"k"</span>], y<span class="op">=</span>metrics[<span class="st">"silhouette"</span>], marker<span class="op">=</span><span class="st">"s"</span>, ax<span class="op">=</span>axes[<span class="dv">1</span>], color<span class="op">=</span><span class="st">"forestgreen"</span>, linewidth<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb3-16"><a href="#cb3-16"></a>axes[<span class="dv">1</span>].set_title(<span class="st">"Evolución del Coeficiente de Silueta"</span>)</span>
<span id="cb3-17"><a href="#cb3-17"></a>axes[<span class="dv">1</span>].set_xlabel(<span class="st">"Número de Grupos (K)"</span>)</span>
<span id="cb3-18"><a href="#cb3-18"></a>axes[<span class="dv">1</span>].set_ylabel(<span class="st">"Puntuación de Silueta"</span>)</span>
<span id="cb3-19"><a href="#cb3-19"></a>axes[<span class="dv">1</span>].grid(<span class="va">True</span>)</span>
<span id="cb3-20"><a href="#cb3-20"></a></span>
<span id="cb3-21"><a href="#cb3-21"></a>plt.tight_layout()</span>
<span id="cb3-22"><a href="#cb3-22"></a>plt.show()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="k-clusters-selection" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="clustering_files/figure-html/k-clusters-selection-output-1.png" width="819" height="817" class="figure-img"></p>
<figcaption>Selección del número de clusters a usar</figcaption>
</figure>
</div>
</div>
</div>
<p>Analicemos estos resultados:</p>
<ul>
<li><p><strong>Coeficiente de Silueta</strong>: Podemos observar un máximo local claramente definido en <span class="math inline">K=4</span>, indicando una buena combinación entre cohesión y separación de los grupos. Aunque el valor máximo absoluto se alcanza en <span class="math inline">K=8</span>, la mejora respecto al valor anterior es poco significativa como para usar este valor en lugar del anterior.</p></li>
<li><p><strong>Método del Codo (Inercia)</strong>: La curva de inercia presenta una desaceleración apreciable en su tasa de disminución alrededor de <span class="math inline">K=4</span>, sugiriendo que incrementos posteriores en el número de clusters producen beneficios progresivamente menores.</p></li>
</ul>
<p>Con base en ambos criterios seleccionamos <span class="math inline">K=4</span> como la configuración final del modelo. Esta elección proporciona un equilibrio adecuado entre calidad estadística e interpretabilidad, permitiendo identificar perfiles delictivos diferenciados sin fragmentar excesivamente el conjunto de 32 entidades federativas analizadas.</p>
</section>
<section id="resultados-de-la-matriz-de-proporciones-y-perfil-de-clusters" class="level1">
<h1>Resultados de la Matriz de Proporciones y Perfil de Clusters</h1>
<p>Una vez entrenado el modelo con <span class="math inline">K=4</span>, se obtuvo la matriz de proporciones promedio para cada cluster, lo que permitió caracterizar los perfiles delictivos predominantes en cada grupo de entidades federativas.</p>
<div id="cell-clustering-matrix-proportions" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Mostrar código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1"></a>N_CLUSTERS_OPTIMO <span class="op">=</span> <span class="dv">4</span></span>
<span id="cb4-2"><a href="#cb4-2"></a></span>
<span id="cb4-3"><a href="#cb4-3"></a><span class="co"># Entrenar el modelo final en 7D y recuperar coordenadas PCA para graficar</span></span>
<span id="cb4-4"><a href="#cb4-4"></a>df_clusters <span class="op">=</span> clustering_pipe.fit_final_model(n_clusters<span class="op">=</span>N_CLUSTERS_OPTIMO)</span>
<span id="cb4-5"><a href="#cb4-5"></a></span>
<span id="cb4-6"><a href="#cb4-6"></a>matrix_pct <span class="op">=</span> clustering_pipe.prepare_matrix(dataframe)</span>
<span id="cb4-7"><a href="#cb4-7"></a></span>
<span id="cb4-8"><a href="#cb4-8"></a><span class="co"># Pegamos la columna del cluster que calculó el modelo</span></span>
<span id="cb4-9"><a href="#cb4-9"></a>matrix_pct[<span class="st">'cluster'</span>] <span class="op">=</span> df_clusters.set_index(<span class="st">'entidad'</span>)[<span class="st">'cluster'</span>]</span>
<span id="cb4-10"><a href="#cb4-10"></a></span>
<span id="cb4-11"><a href="#cb4-11"></a><span class="co"># Calculamos el promedio de cada delito para cada uno de los 4 grupos</span></span>
<span id="cb4-12"><a href="#cb4-12"></a>resumen_clusters <span class="op">=</span> matrix_pct.groupby(<span class="st">'cluster'</span>).mean()</span>
<span id="cb4-13"><a href="#cb4-13"></a></span>
<span id="cb4-14"><a href="#cb4-14"></a><span class="co"># Multiplicamos por 100 para visualizarlo como porcentaje limpio y transponemos para leerlo mejor</span></span>
<span id="cb4-15"><a href="#cb4-15"></a>resumen_porcentual <span class="op">=</span> (resumen_clusters <span class="op">*</span> <span class="dv">100</span>).<span class="bu">round</span>(<span class="dv">2</span>).T</span>
<span id="cb4-16"><a href="#cb4-16"></a>resumen_porcentual</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="clustering-matrix-proportions" class="cell-output cell-output-display" data-execution_count="3">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">cluster</th>
<th data-quarto-table-cell-role="th">0</th>
<th data-quarto-table-cell-role="th">1</th>
<th data-quarto-table-cell-role="th">2</th>
<th data-quarto-table-cell-role="th">3</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">bien_juridico_afectado</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">El patrimonio</th>
<td>44.02</td>
<td>37.44</td>
<td>42.74</td>
<td>55.04</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">La familia</th>
<td>10.57</td>
<td>14.54</td>
<td>19.93</td>
<td>11.17</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">La libertad y la seguridad sexual</th>
<td>3.86</td>
<td>2.22</td>
<td>3.77</td>
<td>2.83</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">La sociedad</th>
<td>0.57</td>
<td>0.53</td>
<td>0.26</td>
<td>0.43</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">La vida y la Integridad corporal</th>
<td>18.74</td>
<td>11.61</td>
<td>13.47</td>
<td>11.08</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Libertad personal</th>
<td>1.05</td>
<td>0.37</td>
<td>1.93</td>
<td>0.69</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Otros bienes jurídicos afectados (del fuero común)</th>
<td>21.19</td>
<td>33.29</td>
<td>17.89</td>
<td>18.76</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="interpretacion-de-los-clusters" class="level1">
<h1>Interpretacion de los Clusters</h1>
<section id="perfil-de-violencia-contra-las-personas" class="level2">
<h2 class="anchored" data-anchor-id="perfil-de-violencia-contra-las-personas">#0 – Perfil de Violencia contra las Personas</h2>
<p>Este grupo se caracteriza por presentar la mayor participación relativa de delitos relacionados con <strong>la vida y la integridad corporal (18.74%)</strong>, así como el valor más elevado en <strong>libertad y seguridad sexual (3.86%)</strong>. En comparación con los demás grupos, la incidencia asociada a conductas violentas tiene un peso relativo mayor dentro de la composición delictiva total. Entre las entidades pertenecientes a este grupo se encuentran Campeche, Chiapas, Guerrero, Michoacán, Estado de México y Oaxaca.</p>
</section>
<section id="perfil-diversificado-de-otros-bienes-jurídicos" class="level2">
<h2 class="anchored" data-anchor-id="perfil-diversificado-de-otros-bienes-jurídicos">#1 – Perfil Diversificado de Otros Bienes Jurídicos</h2>
<p>La característica más distintiva de este grupo es la elevada participación de la categoría <strong>Otros bienes jurídicos afectados (33.29%)</strong>, valor considerablemente superior al observado en los demás clústeres. Esto indica una distribución delictiva menos concentrada en categorías tradicionales como patrimonio o familia y una mayor presencia relativa de delitos clasificados en rubros complementarios del conjunto de datos. Este perfil está conformado por Coahuila, Guanajuato, Tabasco y Yucatán.</p>
</section>
<section id="perfil-familiar-y-de-libertad-personal" class="level2">
<h2 class="anchored" data-anchor-id="perfil-familiar-y-de-libertad-personal">#2 – Perfil Familiar y de Libertad Personal</h2>
<p>Este clúster presenta la mayor proporción de delitos contra <strong>la familia (19.93%)</strong> y contra <strong>la libertad personal (1.93%)</strong>, superando al resto de los grupos en ambas categorías. El resultado sugiere una mayor concentración relativa de problemáticas asociadas al entorno familiar y a conductas que afectan la libertad individual. Las entidades agrupadas bajo este perfil son Chihuahua, Durango, Hidalgo, Nayarit, Nuevo León, Quintana Roo, San Luis Potosí, Sinaloa, Sonora, Tamaulipas, Veracruz y Zacatecas.</p>
</section>
<section id="perfil-patrimonial" class="level2">
<h2 class="anchored" data-anchor-id="perfil-patrimonial">#3 – Perfil Patrimonial</h2>
<p>Este grupo concentra la mayor participación de delitos contra <strong>el patrimonio (55.04%)</strong>, representando más de la mitad de la incidencia promedio del clúster. La composición observada refleja una predominancia de delitos patrimoniales, como robos, fraudes y conductas relacionadas con afectaciones económicas. Entre las entidades pertenecientes a este perfil se encuentran Aguascalientes, Baja California, Baja California Sur, Ciudad de México, Colima, Jalisco, Morelos, Puebla, Querétaro y Tlaxcala.</p>
</section>
<section id="tabla-de-segmentación" class="level2">
<h2 class="anchored" data-anchor-id="tabla-de-segmentación">Tabla de Segmentación</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 38%">
<col style="width: 30%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Clúster</th>
<th style="text-align: left;">Perfil Identificado</th>
<th style="text-align: left;">Entidades Federativas Coincidentes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><strong>0</strong></td>
<td style="text-align: left;">Perfil de Violencia contra las Personas</td>
<td style="text-align: left;">Campeche, Chiapas, Guerrero, Michoacán, México, Oaxaca</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>1</strong></td>
<td style="text-align: left;">Perfil Diversificado / Otros Bienes Jurídicos</td>
<td style="text-align: left;">Coahuila, Guanajuato, Tabasco, Yucatán</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><strong>2</strong></td>
<td style="text-align: left;">Perfil Familiar y Libertad Personal</td>
<td style="text-align: left;">Chihuahua, Durango, Hidalgo, Nayarit, Nuevo León, Quintana Roo, San Luis Potosí, Sinaloa, Sonora, Tamaulipas, Veracruz, Zacatecas</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>3</strong></td>
<td style="text-align: left;">Perfil Patrimonial</td>
<td style="text-align: left;">Aguascalientes, Baja California, Baja California Sur, CDMX, Colima, Jalisco, Morelos, Puebla, Querétaro, Tlaxcala</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="proyección-pca" class="level1">
<h1>Proyección PCA</h1>
<p>A nivel general, la proyección bidimensional permite apreciar que los cuatro grupos identificados por K-Means muestran patrones diferenciados dentro del espacio de características, proporcionando una representación visual coherente con la estructura de agrupamiento obtenida por el modelo.</p>
<div id="cell-clustering-final-visualization" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Mostrar código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1"></a><span class="co"># Construir la visualización del Scatter Plot</span></span>
<span id="cb5-2"><a href="#cb5-2"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">4</span>), dpi<span class="op">=</span>config.PLOT_DPI)</span>
<span id="cb5-3"><a href="#cb5-3"></a></span>
<span id="cb5-4"><a href="#cb5-4"></a>sns.scatterplot(</span>
<span id="cb5-5"><a href="#cb5-5"></a>    data<span class="op">=</span>df_clusters,</span>
<span id="cb5-6"><a href="#cb5-6"></a>    x<span class="op">=</span><span class="st">"pca_1"</span>,</span>
<span id="cb5-7"><a href="#cb5-7"></a>    y<span class="op">=</span><span class="st">"pca_2"</span>,</span>
<span id="cb5-8"><a href="#cb5-8"></a>    hue<span class="op">=</span><span class="st">"cluster"</span>,</span>
<span id="cb5-9"><a href="#cb5-9"></a>    palette<span class="op">=</span><span class="st">"tab10"</span>,</span>
<span id="cb5-10"><a href="#cb5-10"></a>    s<span class="op">=</span><span class="dv">160</span>,</span>
<span id="cb5-11"><a href="#cb5-11"></a>    style<span class="op">=</span><span class="st">"cluster"</span>,</span>
<span id="cb5-12"><a href="#cb5-12"></a>    alpha<span class="op">=</span><span class="fl">0.9</span></span>
<span id="cb5-13"><a href="#cb5-13"></a>)</span>
<span id="cb5-14"><a href="#cb5-14"></a></span>
<span id="cb5-15"><a href="#cb5-15"></a><span class="co"># Etiquetar cada punto con el nombre de su respectivo estado</span></span>
<span id="cb5-16"><a href="#cb5-16"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(df_clusters)):</span>
<span id="cb5-17"><a href="#cb5-17"></a>    plt.text(</span>
<span id="cb5-18"><a href="#cb5-18"></a>        x<span class="op">=</span>df_clusters[<span class="st">"pca_1"</span>][i] <span class="op">+</span> <span class="fl">0.04</span>,</span>
<span id="cb5-19"><a href="#cb5-19"></a>        y<span class="op">=</span>df_clusters[<span class="st">"pca_2"</span>][i] <span class="op">+</span> <span class="fl">0.04</span>,</span>
<span id="cb5-20"><a href="#cb5-20"></a>        s<span class="op">=</span>df_clusters[<span class="st">"entidad"</span>][i],</span>
<span id="cb5-21"><a href="#cb5-21"></a>        fontsize<span class="op">=</span><span class="dv">8</span>,</span>
<span id="cb5-22"><a href="#cb5-22"></a>        alpha<span class="op">=</span><span class="fl">0.8</span></span>
<span id="cb5-23"><a href="#cb5-23"></a>    )</span>
<span id="cb5-24"><a href="#cb5-24"></a></span>
<span id="cb5-25"><a href="#cb5-25"></a>plt.title(<span class="ss">f"Segmentación de Entidades Federativas en </span><span class="sc">{</span>N_CLUSTERS_OPTIMO<span class="sc">}</span><span class="ss"> Perfiles Criminales (Proyección PCA 2D)"</span>)</span>
<span id="cb5-26"><a href="#cb5-26"></a>plt.xlabel(<span class="st">"Componente Principal 1 (Varianza Visual)"</span>)</span>
<span id="cb5-27"><a href="#cb5-27"></a>plt.ylabel(<span class="st">"Componente Principal 2 (Varianza Visual)"</span>)</span>
<span id="cb5-28"><a href="#cb5-28"></a></span>
<span id="cb5-29"><a href="#cb5-29"></a><span class="co"># Líneas de referencia en el origen</span></span>
<span id="cb5-30"><a href="#cb5-30"></a>plt.axhline(<span class="dv">0</span>, color<span class="op">=</span><span class="st">"grey"</span>, linestyle<span class="op">=</span><span class="st">"--"</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb5-31"><a href="#cb5-31"></a>plt.axvline(<span class="dv">0</span>, color<span class="op">=</span><span class="st">"grey"</span>, linestyle<span class="op">=</span><span class="st">"--"</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb5-32"><a href="#cb5-32"></a></span>
<span id="cb5-33"><a href="#cb5-33"></a>plt.tight_layout()</span>
<span id="cb5-34"><a href="#cb5-34"></a>plt.show()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="clustering-final-visualization" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="clustering_files/figure-html/clustering-final-visualization-output-1.png" width="935" height="457" class="figure-img"></p>
<figcaption>Visualización de la Segmentación de Entidades Federativas en 4 Perfiles Criminales (Proyección PCA 2D)</figcaption>
</figure>
</div>
</div>
</div>
<p>Para comprender la geometría de las entidades federativas en la proyección PCA, analizamos la matriz de cargas (loadings), la cual indica la contribución y correlación lineal de cada Bien Jurídico Afectado con las dos primeras componentes principales (ejes del plano).</p>
<table class="caption-top table">
<colgroup>
<col style="width: 27%">
<col style="width: 36%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th>Bien Jurídico Afectado</th>
<th style="text-align: right;">Componente Principal 1 (PC1)</th>
<th style="text-align: right;">Componente Principal 2 (PC2)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>El patrimonio</td>
<td style="text-align: right;">0.567</td>
<td style="text-align: right;">-0.332</td>
</tr>
<tr class="even">
<td>La familia</td>
<td style="text-align: right;">-0.564</td>
<td style="text-align: right;">0.030</td>
</tr>
<tr class="odd">
<td>La libertad y la seguridad sexual</td>
<td style="text-align: right;">-0.459</td>
<td style="text-align: right;">-0.137</td>
</tr>
<tr class="even">
<td>La sociedad</td>
<td style="text-align: right;">-0.047</td>
<td style="text-align: right;">0.322</td>
</tr>
<tr class="odd">
<td>La vida y la integridad corporal</td>
<td style="text-align: right;">-0.095</td>
<td style="text-align: right;">-0.325</td>
</tr>
<tr class="even">
<td>Libertad personal</td>
<td style="text-align: right;">-0.368</td>
<td style="text-align: right;">-0.450</td>
</tr>
<tr class="odd">
<td>Otros bienes jurídicos afectados</td>
<td style="text-align: right;">-0.058</td>
<td style="text-align: right;">0.677</td>
</tr>
</tbody>
</table>
<div id="cell-clustering-pca-loadings" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Mostrar código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1"></a><span class="co"># Extraer la matriz de loadings (componentes_ x variables)</span></span>
<span id="cb6-2"><a href="#cb6-2"></a>loadings <span class="op">=</span> clustering_pipe.pca.components_</span>
<span id="cb6-3"><a href="#cb6-3"></a></span>
<span id="cb6-4"><a href="#cb6-4"></a><span class="co"># Construir un DataFrame elegante para analizar la composición</span></span>
<span id="cb6-5"><a href="#cb6-5"></a>df_loadings <span class="op">=</span> pd.DataFrame(</span>
<span id="cb6-6"><a href="#cb6-6"></a>    loadings.T,  <span class="co"># Transponemos para que las variables queden en las filas</span></span>
<span id="cb6-7"><a href="#cb6-7"></a>    columns<span class="op">=</span>[<span class="st">"Componente Principal 1 (PC1)"</span>, <span class="st">"Componente Principal 2 (PC2)"</span>],</span>
<span id="cb6-8"><a href="#cb6-8"></a>    index<span class="op">=</span>clustering_pipe.features_names</span>
<span id="cb6-9"><a href="#cb6-9"></a>)</span>
<span id="cb6-10"><a href="#cb6-10"></a></span>
<span id="cb6-11"><a href="#cb6-11"></a>df_loadings.<span class="bu">round</span>(<span class="dv">3</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="clustering-pca-loadings" class="cell-output cell-output-display" data-execution_count="5">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Componente Principal 1 (PC1)</th>
<th data-quarto-table-cell-role="th">Componente Principal 2 (PC2)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">El patrimonio</th>
<td>0.567</td>
<td>-0.332</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">La familia</th>
<td>-0.564</td>
<td>0.030</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">La libertad y la seguridad sexual</th>
<td>-0.459</td>
<td>-0.137</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">La sociedad</th>
<td>-0.047</td>
<td>0.322</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">La vida y la Integridad corporal</th>
<td>-0.095</td>
<td>-0.325</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Libertad personal</th>
<td>-0.368</td>
<td>-0.450</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Otros bienes jurídicos afectados (del fuero común)</th>
<td>-0.058</td>
<td>0.677</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Los coeficientes muestran que la Componente Principal 1 (PC1) está dominada por un contraste entre <em>El patrimonio</em> (carga positiva alta) y variables asociadas al entorno familiar y social, como <em>La familia</em> y _La libertad y la seguridad sexual (cargas negativas). En consecuencia, las entidades ubicadas hacia la derecha del plano tienden a presentar una mayor proporción relativa de delitos patrimoniales, mientras que las ubicadas hacia la izquierda muestran una mayor participación relativa de las categorías familiares y sociales.</p>
<p>Por su parte, la Componente Principal 2 (PC2) está fuertemente influenciada por <em>Otros bienes jurídicos afectados</em> (0.677). Esto explica por qué las entidades del Cluster 1 como Yucatán, Coahuila, Guanajuato y Tabasco, aparecen desplazadas hacia la parte superior de la gráfica, pues comparten una participación relativamente elevada de esa categoría respecto al resto del país.</p>
<p>La matriz de cargas también ayuda a interpretar el caso de Tlaxcala, que aparece aislado en la parte inferior derecha. Su ubicación sugiere una combinación de proporciones delictivas distinta a la observada en la mayoría de las entidades de su mismo clúster, aun cuando mantiene una fuerte orientación patrimonial.</p>
<p>La proximidad o aparente solapamiento de algunos puntos pertenecientes a distintos grupos dentro de la proyección bidimensional es un comportamiento esperado ya que la representación mediante PCA conserva únicamente el 55.32% de la varianza total de los datos, dejando fuera aproximadamente el 44.68% de la información contenida en las dimensiones restantes.</p>
</section>
<section id="perfiles-bajo-la-proyección-pca" class="level1">
<h1>Perfiles bajo la Proyección PCA</h1>
<section id="perfil-diversificado" class="level2">
<h2 class="anchored" data-anchor-id="perfil-diversificado">#1 - Perfil Diversificado</h2>
<p>Este grupo, conformado por Yucatán, Coahuila, Guanajuato y Tabasco, es el más claramente distinguible dentro de la proyección PCA, desplazándose hacia la región superior del plano. Esta separación visual resulta consistente con el análisis de los perfiles promedio, ya que corresponde al clúster con la mayor participación de la categoría <strong>Otros bienes jurídicos afectados</strong>, característica que lo diferencia del resto de las entidades federativas.</p>
</section>
<section id="y-2---perfiles-de-violencia-y-entorno-familiar" class="level2">
<h2 class="anchored" data-anchor-id="y-2---perfiles-de-violencia-y-entorno-familiar">#0 y #2 - Perfiles de Violencia y Entorno Familiar</h2>
<p>Ambos grupos ocupan principalmente la región central de la proyección y presentan algunos estados relativamente próximos entre sí. Esta situación sugiere que comparten ciertas características en las dos primeras componentes principales. No obstante, dicha cercanía la debemos interpretar con cuidado ya que la agrupación definitiva fue realizada en el espacio original de siete dimensiones, donde existen diferencias suficientes para que K-Means los clasifique en perfiles distintos.</p>
</section>
<section id="perfil-patrimonial-1" class="level2">
<h2 class="anchored" data-anchor-id="perfil-patrimonial-1">#3 - Perfil Patrimonial</h2>
<p>Este grupo exhibe un núcleo relativamente compacto en la región derecha del plano, donde se concentran entidades como Ciudad de México, Aguascalientes, Querétaro y Jalisco. La cohesión observada resulta consistente con su perfil predominantemente patrimonial, caracterizado por una elevada participación de delitos contra el patrimonio. Adicionalmente, destaca el caso de <strong>Tlaxcala</strong>, que aparece visualmente separado del núcleo principal del grupo. Aunque comparte la misma clasificación patrimonial, su ubicación sugiere una combinación de proporciones delictivas distinta a la observada en el resto de las entidades del clúster.</p>
<p>Podemos notar que algunos puntos pertenecientes a distintos grupos aparecen próximos entre sí dentro de la proyección bidimensional. Este comportamiento es esperado, ya que la representación mediante PCA conserva únicamente el 55.32% de la varianza total de los datos, dejando fuera aproximadamente el 44.68% de la información contenida en las dimensiones restantes.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button,
          { trigger: "manual",
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config);
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined;
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              }
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            }
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Facultad de Ciencias, Ciencias de la Computación, UNAM</p>
</div>
    <div class="nav-footer-center">
<p>© 2026 Méndez Ávila, Paredes Zamudio y Sánchez Rosas</p>
<div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/wallsified/proyecto-final-aymdd&quot;/edit/main/chapters/clustering.qmd" class="toc-action"><i class="bi bi-github"></i>Editar esta página</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Almacenes y Minería de Datos 26-2</p>
</div>
  </div>
</footer>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>